apiVersion: v1
kind: Service
metadata:
  name: nodek8sapp-service
  namespace: nodek8sapp
  labels:
    app: nodek8sapp
spec:
  type: NodePort
  selector:
    app: nodek8sapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30301
